version: "3"

services:
  next-app:
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000
    networks:
      - dokploy-network
      #- default
    labels:
       - traefik.enable=true
       #- traefik.docker.network=dokploy-network

       # Enrutamiento HTTP a HTTPS
       - traefik.http.routers.testing-composer.rule=Host(`testing-composer.gameinis.com`)
       - traefik.http.routers.testing-composer.entrypoints=web
       - traefik.http.routers.testing-composer.middlewares=redirect-to-https@file

       # Enrutamiento HTTPS (Seguro)
       - traefik.http.routers.testing-composer-secure.rule=Host(`testing-composer.gameinis.com`)
       - traefik.http.routers.testing-composer-secure.entrypoints=websecure
       - traefik.http.routers.testing-composer-secure.tls.certresolver=letsencrypt

       # Conexión al puerto interno de tu app
       - traefik.http.services.testing-composer-secure.loadbalancer.server.port=3000
networks:
  dokploy-network:
    external: true
